---
# File: tasks/ssl.yml - SSL tasks for ansible-playbook-rabbitmq

- name: create the ssl folder for rabbitmq
  file:
    path: /etc/rabbitmq/ssl/
    owner: rabbitmq
    group: rabbitmq
    mode: 0750
    state: directory

- name: copy the ssl certificates
  copy:
    src: files/rabbitmq_{{ item }}.pem
    dest: /etc/rabbitmq/ssl/{{ item }}.pem
    owner: rabbitmq
    group: rabbitmq
    mode: 0640
    backup: yes
  with_items:
    - "{{ rabbitmq_cacert }}"
    - "{{ rabbitmq_server_key }}"
    - "{{ rabbitmq_server_cert }}"
